import javax.swing.*;
import java.awt.*;
import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.util.*;
import org.json.*;
import java.net.URL;
import java.net.HttpURLConnection;
import java.io.BufferedReader;
import java.io.InputStreamReader;

/**
 *
 * @author Hinokaa
 */
public class CekCuacaFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CekCuacaFrame.class.getName());
    private DefaultTableModel model;
    private Map<String, String[]> dataCuaca; // Simulasi data cuaca
    private java.util.List<String> favoritList = new ArrayList<>();

    /**
     * Creates new form CekCuacaFrame
     */
    public CekCuacaFrame() {
        initComponents();
        initCustom();
    }
     private void initCustom() {
        // Atur model tabel
        model = (DefaultTableModel) tableCuaca.getModel();
        model.setRowCount(0);
    }
     private JSONObject getWeatherData(String kota) {
        String apiKey = "760c6ade700130e926f271e9ceb6513f"; // Ganti dengan API key-mu
        String urlString = String.format(
                "https://api.openweathermap.org/data/2.5/weather?q=%s&units=metric&appid=%s",
                kota, apiKey
        );

        try {
            URL url = new URL(urlString);
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("GET");
            conn.connect();

            int responseCode = conn.getResponseCode();
            if (responseCode != 200) {
                JOptionPane.showMessageDialog(this, "Kota tidak ditemukan atau API error!");
                return null;
            }

            BufferedReader in = new BufferedReader(new InputStreamReader(conn.getInputStream()));
            StringBuilder content = new StringBuilder();
            String inputLine;
            while ((inputLine = in.readLine()) != null) {
                content.append(inputLine);
            }
            in.close();
            conn.disconnect();

            return new JSONObject(content.toString());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mengambil data: " + e.getMessage());
            return null;
        }
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCuaca = new javax.swing.JTable();
        comboFavorit = new javax.swing.JComboBox<>();
        btnExportCSV = new javax.swing.JButton();
        btnImportCSV = new javax.swing.JButton();
        btnCekCuaca = new javax.swing.JButton();
        btnSimpanFavorit = new javax.swing.JButton();
        txtKota = new javax.swing.JTextField();
        labelJudul2 = new javax.swing.JLabel();
        labelJudul = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        labelSuhu = new javax.swing.JLabel();
        labelKondisi = new javax.swing.JLabel();
        labelIcon = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        tableCuaca.setBackground(new java.awt.Color(204, 255, 255));
        tableCuaca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "City", "Temperature", "Condition"
            }
        ));
        jScrollPane2.setViewportView(tableCuaca);

        comboFavorit.setBackground(new java.awt.Color(204, 255, 255));

        btnExportCSV.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnExportCSV.setForeground(new java.awt.Color(153, 204, 255));
        btnExportCSV.setText("Export");
        btnExportCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportCSVActionPerformed(evt);
            }
        });

        btnImportCSV.setBackground(new java.awt.Color(153, 204, 255));
        btnImportCSV.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnImportCSV.setForeground(new java.awt.Color(255, 255, 255));
        btnImportCSV.setText("Import");
        btnImportCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportCSVActionPerformed(evt);
            }
        });

        btnCekCuaca.setBackground(new java.awt.Color(153, 204, 255));
        btnCekCuaca.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnCekCuaca.setForeground(new java.awt.Color(255, 255, 255));
        btnCekCuaca.setText("Check");
        btnCekCuaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekCuacaActionPerformed(evt);
            }
        });

        btnSimpanFavorit.setBackground(new java.awt.Color(204, 255, 255));
        btnSimpanFavorit.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnSimpanFavorit.setForeground(new java.awt.Color(153, 204, 255));
        btnSimpanFavorit.setText("Favorite");
        btnSimpanFavorit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanFavoritActionPerformed(evt);
            }
        });

        txtKota.setBackground(new java.awt.Color(204, 255, 255));

        labelJudul2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        labelJudul2.setForeground(new java.awt.Color(255, 255, 255));
        labelJudul2.setText("Checker\n");

        labelJudul.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        labelJudul.setForeground(new java.awt.Color(51, 255, 255));
        labelJudul.setText("Weather");

        jLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel.setForeground(new java.awt.Color(255, 255, 255));
        jLabel.setText("City Name :");

        labelSuhu.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        labelSuhu.setForeground(new java.awt.Color(255, 255, 255));
        labelSuhu.setText("Temperature : c");

        labelKondisi.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        labelKondisi.setForeground(new java.awt.Color(255, 255, 255));
        labelKondisi.setText("Condition : ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addComponent(labelJudul)
                                    .addGap(4, 4, 4)
                                    .addComponent(labelJudul2)
                                    .addGap(97, 97, 97))
                                .addComponent(labelSuhu)
                                .addComponent(labelKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel)
                                    .addGap(95, 95, 95)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(btnCekCuaca, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnSimpanFavorit))
                                        .addComponent(txtKota)))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btnImportCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnExportCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(67, 67, 67)
                            .addComponent(comboFavorit, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(23, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelJudul2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel)
                        .addComponent(txtKota, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCekCuaca)
                        .addComponent(btnSimpanFavorit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(14, 14, 14)
                    .addComponent(labelSuhu)
                    .addGap(24, 24, 24)
                    .addComponent(labelKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(159, 159, 159)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnImportCSV)
                        .addComponent(btnExportCSV)
                        .addComponent(comboFavorit))
                    .addGap(17, 17, 17)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportCSVActionPerformed
       
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Simpan Data Cuaca");
        int result = fileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            try (PrintWriter writer = new PrintWriter(fileChooser.getSelectedFile())) {
                writer.println("City,Temperature,Condition");
                for (int i = 0; i < model.getRowCount(); i++) {
                    writer.println(model.getValueAt(i, 0) + "," + model.getValueAt(i, 1) + "," + model.getValueAt(i, 2));
                }
                JOptionPane.showMessageDialog(this, "Data berhasil diexport!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal export data: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnExportCSVActionPerformed

    private void btnImportCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportCSVActionPerformed
       JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Pilih File CSV");
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                model.setRowCount(0);
                String line;
                br.readLine(); // skip header
                while ((line = br.readLine()) != null) {
                    String[] data = line.split(",");
                    model.addRow(data);
                }
                JOptionPane.showMessageDialog(this, "Data berhasil diimport!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal import data: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnImportCSVActionPerformed

    private void btnCekCuacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekCuacaActionPerformed
          String kota = txtKota.getText().trim();
        if (kota.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan nama kota terlebih dahulu!");
            return;
        }

        JSONObject json = getWeatherData(kota);
        if (json == null) return;

        try {
            double suhu = json.getJSONObject("main").getDouble("temp");
            String kondisi = json.getJSONArray("weather").getJSONObject(0).getString("main");

            labelSuhu.setText("Temperature : " + suhu + " °C");
            labelKondisi.setText("Condition : " + kondisi);

            model.addRow(new Object[]{kota, suhu + " °C", kondisi});

            // tampilkan ikon
            String iconPath = "/icons/default.png";
            switch (kondisi.toLowerCase()) {
                case "clear":
                case "sunny": iconPath = "/icons/Sunny.png"; break;
                case "clouds":
                case "cloudy": iconPath = "/icons/Cloudy.png"; break;
                case "rain":
                case "drizzle": iconPath = "/icons/Rainy.png"; break;
                case "wind":
                case "windy": iconPath = "/icons/Windy.png"; break;
                case "hot": iconPath = "/icons/Hot.png"; break;
            }

            try {
                ImageIcon icon = new ImageIcon(getClass().getResource(iconPath));
                Image img = icon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
                labelIcon.setIcon(new ImageIcon(img));
            } catch (Exception ex) {
                System.out.println("Ikon tidak ditemukan: " + iconPath);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat membaca data!");
        }
    
    }//GEN-LAST:event_btnCekCuacaActionPerformed

    private void btnSimpanFavoritActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanFavoritActionPerformed
        String kota = txtKota.getText().trim();
        if (kota.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan nama kota dulu!");
            return;
        }

        if (!favoritList.contains(kota)) {
            favoritList.add(kota);
            comboFavorit.addItem(kota);
            JOptionPane.showMessageDialog(this, kota + " ditambahkan ke favorit!");
        } else {
            JOptionPane.showMessageDialog(this, kota + " sudah ada di favorit.");
        }
    }//GEN-LAST:event_btnSimpanFavoritActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new CekCuacaFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCekCuaca;
    private javax.swing.JButton btnExportCSV;
    private javax.swing.JButton btnImportCSV;
    private javax.swing.JButton btnSimpanFavorit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboFavorit;
    private javax.swing.JLabel jLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelIcon;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelJudul2;
    private javax.swing.JLabel labelKondisi;
    private javax.swing.JLabel labelSuhu;
    private javax.swing.JTable tableCuaca;
    private javax.swing.JTextField txtKota;
    // End of variables declaration//GEN-END:variables
}
